baseURL = 'https://myblogs-2uy.pages.dev/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = 'hello-friend-ng'


[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"